# Generated by Django 2.0.6 on 2018-11-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_remove_permission_group_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='display',
            field=models.BooleanField(default=True, verbose_name='权限是否显示在菜单栏(true:显示，flase:不显示)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='rbac.Permission', verbose_name='请选择角色拥有的权限：'),
        ),
    ]
