# Generated by Django 2.0 on 2018-11-23 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('excel_name', models.CharField(max_length=32, verbose_name='文件名称')),
                ('sheet_num', models.IntegerField(max_length=32, verbose_name='包含的sheet数')),
                ('flag', models.BooleanField(default=False, max_length=32, verbose_name='执行状态')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='Txt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt_name', models.CharField(max_length=32, verbose_name='文件名称')),
                ('txt_result', models.IntegerField(max_length=32, verbose_name='wc -l /data/logs/tmp_log/guantie_everyday_result/crawl_2018-09-02.txt 执行结果')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='处理完成时间')),
            ],
            options={
                'verbose_name_plural': '生成文件表',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='txt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_file.Txt', verbose_name='对应生成的txt'),
        ),
    ]
