# Generated by Django 2.0 on 2018-11-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='sheet_num',
            field=models.IntegerField(verbose_name='包含的sheet数'),
        ),
    ]
