# Generated by Django 2.0 on 2018-11-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_auto_20181123_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txt',
            name='txt_result',
            field=models.CharField(max_length=32, verbose_name='wc -l /data/logs/tmp_log/guantie_everyday_result/crawl_2018-09-02.txt 执行结果'),
        ),
    ]
