# Generated by Django 2.0 on 2018-11-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0003_auto_20181123_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txt',
            name='date',
            field=models.CharField(max_length=32, verbose_name='对应hive时间'),
        ),
    ]
