# Generated by Django 2.0 on 2018-11-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0004_auto_20181123_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txt',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='对应hive时间'),
        ),
    ]
