# Generated by Django 2.0 on 2018-11-26 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0006_auto_20181126_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name_plural': '上传EXCEL文件表'},
        ),
        migrations.AlterModelOptions(
            name='txt',
            options={'verbose_name_plural': '生成txt文件表'},
        ),
    ]
