# Generated by Django 2.0 on 2018-11-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0008_auto_20181126_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='excel_name',
            field=models.CharField(max_length=200, verbose_name='文件名称'),
        ),
    ]
