# Generated by Django 2.0 on 2018-11-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0010_auto_20181126_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='txt_id',
            new_name='txt',
        ),
    ]
