# Generated by Django 2.0 on 2018-11-27 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0011_auto_20181126_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='txt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_file.Txt', unique=True, verbose_name='对应生成的txt'),
        ),
    ]
